CREATE TABLE `post_to_post` (
	`parent_post_id` text NOT NULL,
	`child_post_id` text NOT NULL,
	PRIMARY KEY(`child_post_id`, `parent_post_id`),
	FOREIGN KEY (`parent_post_id`) REFERENCES `posts`(`id`) ON UPDATE cascade ON DELETE cascade,
	FOREIGN KEY (`child_post_id`) REFERENCES `posts`(`id`) ON UPDATE cascade ON DELETE cascade
);
--> statement-breakpoint
CREATE TABLE `posts` (
	`id` text PRIMARY KEY NOT NULL,
	`post_id` text NOT NULL,
	`group_id` text,
	`group_name` text,
	`post_text` text NOT NULL,
	`post_url` text,
	`post_attachments` text,
	`phone_numbers` text,
	`created_at` real DEFAULT (strftime('%s', 'now')) NOT NULL,
	`updated_at` real DEFAULT (strftime('%s', 'now')) NOT NULL,
	`post_creation_time` real DEFAULT (strftime('%s', 'now')) NOT NULL,
	`processing_status` text DEFAULT 'pending' NOT NULL,
	`property_type` text,
	`listing_type` text,
	`rental_type` text,
	`location` text DEFAULT '' NOT NULL,
	`price` real,
	`size_in_m2` real,
	`number_of_floors` integer,
	`number_of_rooms` integer,
	`number_of_bedrooms` integer,
	`has_parking` integer,
	`has_garden` integer,
	`is_full_furnished` integer,
	`is_partially_furnished` integer,
	`does_price_include_electricity` integer,
	`does_price_include_water` integer,
	`does_price_include_local_taxes` integer,
	`available_from` text,
	`showing_date` text,
	`showing_time` text,
	`is_by_broker_or_agent` integer,
	`summary` text DEFAULT '' NOT NULL,
	`post_description` text DEFAULT '' NOT NULL,
	`post_location` text,
	`listing_size` text,
	`post_price` text,
	`post_extra_details` text,
	`post_contact_info` text,
	`publisher_name` text,
	`publisher_url` text,
	`publisher_id` text,
	`reaction_count` integer DEFAULT 0,
	`is_marked_as_irelevant` integer
);
--> statement-breakpoint
CREATE UNIQUE INDEX `posts_post_id_unique` ON `posts` (`post_id`);