CREATE TABLE `posts` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`post_id` text NOT NULL,
	`post_text` text NOT NULL,
	`post_author` text,
	`post_author_id` text,
	`post_author_url` text,
	`post_url` text,
	`post_date` text,
	`post_images` text,
	`post_videos` text,
	`post_links` text,
	`email` text,
	`first_name` text,
	`last_name` text,
	`comment_count` integer DEFAULT 0,
	`has_shared_content` integer DEFAULT false,
	`shared_post` text,
	`title` text,
	`is_house_rental_listing` integer,
	`location` text,
	`city` text,
	`neighborhood` text,
	`village` text,
	`price` real,
	`is_price_flexible` integer,
	`has_price` integer,
	`is_house` integer,
	`is_apartment` integer,
	`size_in_m2` real,
	`garden_size_in_m2` real,
	`built_house_size_in_m2` real,
	`number_of_floors` integer,
	`number_of_rooms` real,
	`number_of_bedrooms` integer,
	`number_of_bathrooms` integer,
	`is_for_long_term` integer,
	`has_parking` integer,
	`has_garden` integer,
	`is_garden_maintained` integer,
	`has_pool` integer,
	`has_balcony` integer,
	`has_view` integer,
	`is_full_furnished` integer,
	`is_partially_furnished` integer,
	`does_price_include_all_utilities` integer,
	`does_price_include_internet` integer,
	`does_price_include_electricity` integer,
	`does_price_include_water` integer,
	`does_price_include_local_taxes` integer,
	`availible_from` text,
	`is_available_now` integer,
	`showing_date` text,
	`showing_time` text,
	`is_new_construction` integer,
	`is_renovated` integer,
	`phone_numbers` text,
	`is_by_broker_or_agent` integer,
	`created_at` text DEFAULT CURRENT_TIMESTAMP,
	`updated_at` text DEFAULT CURRENT_TIMESTAMP,
	`processed_at` text
);
--> statement-breakpoint
CREATE UNIQUE INDEX `posts_post_id_unique` ON `posts` (`post_id`);